// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: batch.go

package sqlcgen

import (
	"context"
	"errors"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	decimal "github.com/shopspring/decimal"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const balanceTransaction_Create = `-- name: BalanceTransaction_Create :batchexec
INSERT INTO balance_transactions
    (user_id, order_id, amount, direction)
VALUES
    ($1, $2, $3, $4::balance_transaction_type)
`

type BalanceTransaction_CreateBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type BalanceTransaction_CreateParams struct {
	UserID    int64
	OrderID   pgtype.Int8
	Amount    decimal.Decimal
	Direction BalanceTransactionType
}

func (q *Queries) BalanceTransaction_Create(ctx context.Context, arg []BalanceTransaction_CreateParams) *BalanceTransaction_CreateBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.UserID,
			a.OrderID,
			a.Amount,
			a.Direction,
		}
		batch.Queue(balanceTransaction_Create, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &BalanceTransaction_CreateBatchResults{br, len(arg), false}
}

func (b *BalanceTransaction_CreateBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *BalanceTransaction_CreateBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const orders_UpdateWithAccrualData = `-- name: Orders_UpdateWithAccrualData :batchone
UPDATE orders SET status = $1, accrual = $2 WHERE id = $3 RETURNING id, created_at, updated_at, user_id, order_code, status, accrual
`

type Orders_UpdateWithAccrualDataBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type Orders_UpdateWithAccrualDataParams struct {
	Status  OrderStatusType
	Accrual decimal.Decimal
	ID      int64
}

func (q *Queries) Orders_UpdateWithAccrualData(ctx context.Context, arg []Orders_UpdateWithAccrualDataParams) *Orders_UpdateWithAccrualDataBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.Status,
			a.Accrual,
			a.ID,
		}
		batch.Queue(orders_UpdateWithAccrualData, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &Orders_UpdateWithAccrualDataBatchResults{br, len(arg), false}
}

func (b *Orders_UpdateWithAccrualDataBatchResults) QueryRow(f func(int, Order, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		var i Order
		if b.closed {
			if f != nil {
				f(t, i, ErrBatchAlreadyClosed)
			}
			continue
		}
		row := b.br.QueryRow()
		err := row.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.OrderCode,
			&i.Status,
			&i.Accrual,
		)
		if f != nil {
			f(t, i, err)
		}
	}
}

func (b *Orders_UpdateWithAccrualDataBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
