CREATE TYPE order_status_type AS ENUM('PROCESSED', 'PROCESSING', 'INVALID', 'NEW');
CREATE TABLE orders (
    ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
    order_code VARCHAR(20) NOT NULL,
    status order_status_type NOT NULL DEFAULT 'NEW',
    accrual DECIMAL(10,2) NOT NULL DEFAULT 0
);

CREATE UNIQUE INDEX idx_uniq_order_code ON orders(order_code);